/*
 * echo.c -- bare-metal UDP echo firmware for VexRiscv
 *
 * Loaded by the LiteX BIOS over serial after the FPGA is programmed.
 * Polls for incoming UDP packets on ECHO_PORT, writes each payload
 * into the EchoSlave BRAM, reads it back, and sends the reply.
 *
 * The round-trip through the slave (write then read-back) is intentional.
 * Replying from the slave's output, not from the input buffer, proves that
 * data actually reached the hardware and came back. A broken slave breaks
 * the echo visibly.
 *
 * FPGA address: 192.168.1.101 / port 1234
 * Host address: anything on 192.168.1.0/24
 *
 * Build: see Makefile in this directory.
 * Load:  litex_term --kernel firmware.bin /dev/ttyUSB0
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include <generated/csr.h>   /* CSR accessors generated by build_soc.py  */
#include <generated/mem.h>   /* ECHOSLAVE_BASE, ETHMAC_BASE etc.          */

#include <libliteeth/udp.h>  /* udp_start / udp_service / udp_send etc.  */

/* FPGA's network identity. The host sends packets to this MAC and IP. */
static const unsigned char fpga_mac[6] = {0x02, 0x00, 0x00, 0x00, 0x00, 0x01};
static const unsigned int  fpga_ip     = IPTOINT(192, 168, 1, 101);

/* UDP port the echo listens on. */
#define ECHO_PORT 1234

/*
 * The EchoSlave sits at ECHOSLAVE_BASE (defined in generated/mem.h by LiteX
 * from the region name "echoslave" in build_soc.py). If it is somehow absent
 * from the generated header, the build will fail with a clear error here.
 */
#ifndef ECHOSLAVE_BASE
#error "ECHOSLAVE_BASE not defined -- run build_soc.py to generate mem.h"
#endif

/* Write one 32-bit word to the slave at word index 'offset'. */
static inline void slave_write(unsigned int offset, unsigned int value)
{
    volatile unsigned int *slave = (volatile unsigned int *)ECHOSLAVE_BASE;
    slave[offset] = value;
}

/* Read one 32-bit word back from the slave. */
static inline unsigned int slave_read(unsigned int offset)
{
    volatile unsigned int *slave = (volatile unsigned int *)ECHOSLAVE_BASE;
    return slave[offset];
}

/*
 * Pending reply state.
 *
 * udp_send() sends to cached_ip/cached_mac in udp.c, which is only populated
 * by udp_arp_resolve(). The cache is never updated from incoming packets, so
 * calling udp_send() directly from the RX callback silently fails (returns 0).
 * udp_arp_resolve() internally calls udp_service(), which would re-enter the
 * callback while the current frame is still being processed.
 *
 * Solution: the callback saves the reply parameters and returns immediately.
 * The main loop calls udp_arp_resolve() + udp_send() safely between frames.
 */
static volatile uint32_t pending_src_ip;
static volatile uint16_t pending_src_port;
static volatile uint16_t pending_dst_port;
static volatile uint32_t pending_length;
static volatile int      pending_reply;

/*
 * echo_rx -- UDP receive callback.
 *
 * Writes the payload into the EchoSlave word by word, then signals the main
 * loop to send the reply. The BRAM holds the data until the main loop reads
 * it back -- nothing else writes to it in between.
 */
static void echo_rx(uint32_t src_ip,
                    uint16_t src_port,
                    uint16_t dst_port,
                    void *data, uint32_t length)
{
    if (dst_port != ECHO_PORT)
        return;

    /* D8 on: RX callback fired on port 1234 */
    debug_leds_out_write(debug_leds_out_read() | 0x04);

    unsigned char *in   = (unsigned char *)data;
    unsigned int   words = (length + 3) / 4;

    for (unsigned int i = 0; i < words; i++) {
        unsigned int w = 0;
        memcpy(&w, in + i * 4, 4);
        slave_write(i, w);
    }

    pending_src_ip   = src_ip;
    pending_src_port = src_port;
    pending_dst_port = dst_port;
    pending_length   = length;
    pending_reply    = 1;
}

int main(void)
{
    /* D6 on: firmware reached main() */
    debug_leds_out_write(0x01);

    /* Enable the free-running timer used by the UDP stack. */
    timer0_en_write(0);
    timer0_reload_write(0);
    timer0_load_write(0);
    timer0_en_write(1);

    udp_start(fpga_mac, fpga_ip);

    /* D7 on: udp_start() returned -- PHY linked and MAC initialized */
    debug_leds_out_write(0x03);

    pending_reply = 0;
    udp_set_callback(echo_rx);

    while (1) {
        udp_service();

        if (pending_reply) {
            pending_reply = 0;

            /* Resolve the sender's MAC (fast path if already cached). */
            if (!udp_arp_resolve(pending_src_ip))
                continue;

            /* Read payload back from the slave into the TX buffer. */
            unsigned char *out   = (unsigned char *)udp_get_tx_buffer();
            unsigned int   words = (pending_length + 3) / 4;
            for (unsigned int i = 0; i < words; i++) {
                unsigned int w = slave_read(i);
                memcpy(out + i * 4, &w, 4);
            }

            udp_send(pending_dst_port, pending_src_port, pending_length);

            /* D9 on: reply sent */
            debug_leds_out_write(debug_leds_out_read() | 0x08);
        }
    }

    return 0;
}
