/*
 * echo.c -- bare-metal UDP echo firmware for VexRiscv
 *
 * Loaded by the LiteX BIOS over serial after the FPGA is programmed.
 * Polls for incoming UDP packets on ECHO_PORT, writes each payload
 * into the EchoSlave BRAM, reads it back, and sends the reply.
 *
 * The round-trip through the slave (write then read-back) is intentional.
 * Replying from the slave's output, not from the input buffer, proves that
 * data actually reached the hardware and came back. A broken slave breaks
 * the echo visibly.
 *
 * FPGA address: 192.168.1.101 / port 1234
 * Host address: anything on 192.168.1.0/24
 *
 * Build: see Makefile in this directory.
 * Load:  litex_term --kernel firmware.bin /dev/ttyUSB0
 */

#include <stdio.h>
#include <string.h>

#include <generated/csr.h>   /* CSR accessors generated by build_soc.py  */
#include <generated/mem.h>   /* ECHOSLAVE_BASE, ETHMAC_BASE etc.          */

#include <libliteeth/udp.h>  /* udp_start / udp_service / udp_send etc.  */

/* FPGA's network identity. The host sends packets to this MAC and IP. */
static const unsigned char fpga_mac[6] = {0x02, 0x00, 0x00, 0x00, 0x00, 0x01};
static const unsigned int  fpga_ip     = IPTOINT(192, 168, 1, 101);

/* UDP port the echo listens on. */
#define ECHO_PORT 1234

/*
 * The EchoSlave sits at ECHOSLAVE_BASE (defined in generated/mem.h by LiteX
 * from the region name "echoslave" in build_soc.py). If it is somehow absent
 * from the generated header, the build will fail with a clear error here.
 */
#ifndef ECHOSLAVE_BASE
#error "ECHOSLAVE_BASE not defined -- run build_soc.py to generate mem.h"
#endif

/* Write one 32-bit word to the slave at word index 'offset'. */
static inline void slave_write(unsigned int offset, unsigned int value)
{
    volatile unsigned int *slave = (volatile unsigned int *)ECHOSLAVE_BASE;
    slave[offset] = value;
}

/* Read one 32-bit word back from the slave. */
static inline unsigned int slave_read(unsigned int offset)
{
    volatile unsigned int *slave = (volatile unsigned int *)ECHOSLAVE_BASE;
    return slave[offset];
}

/*
 * echo_rx -- UDP receive callback.
 *
 * The stack calls this for every received packet. We:
 *   1. Drop anything not on ECHO_PORT.
 *   2. Write the payload into the EchoSlave word by word.
 *   3. Read it back OUT OF THE SLAVE into the transmit buffer.
 *   4. Send the reply.
 *
 * Step 3 is the critical discipline: the outgoing bytes come from the slave,
 * never from the incoming pointer. That is what puts the slave in the path.
 */
static void echo_rx(unsigned int src_ip,
                    unsigned short src_port,
                    unsigned short dst_port,
                    void *data, unsigned int length)
{
    if (dst_port != ECHO_PORT)
        return;

    /* D8 on: RX callback fired on port 1234 */
    debug_leds_out_write(debug_leds_out_read() | 0x04);

    unsigned char *in   = (unsigned char *)data;
    unsigned int   words = (length + 3) / 4;

    /* 1. Write received payload into the slave. */
    for (unsigned int i = 0; i < words; i++) {
        unsigned int w = 0;
        memcpy(&w, in + i * 4, 4);
        slave_write(i, w);
    }

    /* 2. Read back from the slave into the UDP transmit buffer. */
    unsigned char *out = (unsigned char *)udp_get_tx_buffer();
    for (unsigned int i = 0; i < words; i++) {
        unsigned int w = slave_read(i);
        memcpy(out + i * 4, &w, 4);
    }

    /* 3. Send the reply back to whoever sent this packet. */
    udp_send(dst_port, src_port, length);

    /* D9 on: reply sent */
    debug_leds_out_write(debug_leds_out_read() | 0x08);
}

int main(void)
{
    /* D6 on: firmware reached main() */
    debug_leds_out_write(0x01);

    /* Enable the free-running timer used by the UDP stack. */
    timer0_en_write(0);
    timer0_reload_write(0);
    timer0_load_write(0);
    timer0_en_write(1);

    udp_start(fpga_mac, fpga_ip);

    /* D7 on: udp_start() returned -- PHY linked and MAC initialized */
    debug_leds_out_write(0x03);

    udp_set_callback(echo_rx);

    /* printf removed -- UART may block before udp_service() is reached */

    while (1)
        udp_service();

    return 0;
}
